version: "2"
services:
    client:
        image: node/current-alpine
        restart: always
        context: ../../
        ports:
            - "3000:3000"
        working_dir: /client/src/app
        volumes:
            - ./client:/client/src/app
        entrypoint: ["npm", "start"]
        links:
            - server
        networks:
            - webappnetwork
    server:
        image: node/current-alpine
        restart: always
        context: ../../
        ports:
            - "7000:7000"
        volumes:
            - ./server:/server
            - /server/node_modules
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge
